development:
  adapter: postgresql
  encoding: unicode
  database: pharm2doctor_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: pharm2doctor_test
  pool: 5
  timeout: 5000

